{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "41fc91d9-e0ec-4186-8330-752b0d55eae5",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import tensorflow as tf\n",
    "import numpy as np\n",
    "from PIL import Image\n",
    "\n",
    "# ---------------- PAGE CONFIG ----------------\n",
    "st.set_page_config(\n",
    "    page_title=\"Kisan AI Doctor\",\n",
    "    page_icon=\"🌾\",\n",
    "    layout=\"centered\"\n",
    ")\n",
    "\n",
    "# ---------------- LOAD MODEL ----------------\n",
    "@st.cache_resource\n",
    "def load_model():\n",
    "    return tf.keras.models.load_model(\"best_crop_model.keras\")\n",
    "\n",
    "model = load_model()\n",
    "\n",
    "class_names = ['Healthy', 'Powdery', 'Rust']\n",
    "\n",
    "# ---------------- SIDEBAR ----------------\n",
    "st.sidebar.title(\"🌾 About\")\n",
    "st.sidebar.info(\"AI-based Crop Disease Detection System\")\n",
    "\n",
    "# ---------------- HEADER ----------------\n",
    "st.title(\"🌾 Kisan AI Doctor\")\n",
    "st.markdown(\"### 📷 पत्ते की साफ फोटो अपलोड करें\")\n",
    "st.markdown(\"---\")\n",
    "\n",
    "uploaded_file = st.file_uploader(\n",
    "    \"Leaf Image Upload Kare (JPG / PNG)\",\n",
    "    type=[\"jpg\", \"png\", \"jpeg\"]\n",
    ")\n",
    "\n",
    "# ---------------- MAIN LOGIC ----------------\n",
    "if uploaded_file is not None:\n",
    "\n",
    "    try:\n",
    "        # Load image\n",
    "        img = Image.open(uploaded_file).convert(\"RGB\")\n",
    "        st.image(img, caption=\"Uploaded Image\", use_container_width=True)\n",
    "\n",
    "        # -------- Preprocessing --------\n",
    "        img_resized = img.resize((224, 224))\n",
    "        img_array = np.array(img_resized)\n",
    "\n",
    "        # IMPORTANT:\n",
    "        # Agar model me Rescaling(1./255) hai → yaha normalization mat karo\n",
    "\n",
    "        img_array = np.expand_dims(img_array, axis=0)\n",
    "\n",
    "        # -------- Prediction --------\n",
    "        prediction = model.predict(img_array)\n",
    "        predicted_index = np.argmax(prediction)\n",
    "        predicted_class = class_names[predicted_index]\n",
    "        confidence = float(np.max(prediction)) * 100\n",
    "\n",
    "        st.markdown(\"---\")\n",
    "        st.subheader(\"🔍 Prediction Result\")\n",
    "\n",
    "        # Show all probabilities\n",
    "        for i, cls in enumerate(class_names):\n",
    "            st.write(f\"{cls}: {prediction[0][i]*100:.2f}%\")\n",
    "\n",
    "        st.progress(int(confidence))\n",
    "\n",
    "        if confidence < 60:\n",
    "            st.warning(\"⚠️ Model unsure hai. Clear image upload karein.\")\n",
    "        else:\n",
    "            st.success(f\"🌿 Disease: {predicted_class}\")\n",
    "            st.info(f\"Confidence: {confidence:.2f}%\")\n",
    "\n",
    "            # -------- Chat Button --------\n",
    "            if st.button(\"💬 Get Treatment Advice\"):\n",
    "\n",
    "                st.markdown(\"### 💊 Treatment Suggestion\")\n",
    "\n",
    "                if predicted_class == \"Powdery\":\n",
    "                    st.write(\"• Sulfur based fungicide spray karein.\")\n",
    "                    st.write(\"• 7 din baad repeat karein.\")\n",
    "                    st.write(\"• Humidity kam rakhein.\")\n",
    "\n",
    "                elif predicted_class == \"Rust\":\n",
    "                    st.write(\"• Copper fungicide use karein.\")\n",
    "                    st.write(\"• Affected leaves hata dein.\")\n",
    "                    st.write(\"• Proper sunlight ensure karein.\")\n",
    "\n",
    "                else:\n",
    "                    st.success(\"🌱 Plant healthy hai. Regular monitoring karein.\")\n",
    "\n",
    "    except:\n",
    "        st.error(\"❌ Image process nahi ho payi. Dusri image try karein.\")\n",
    "\n",
    "# ---------------- FOOTER ----------------\n",
    "st.markdown(\"---\")\n",
    "st.caption(\"Developed by Raj 🌾 | AI Powered Crop Disease Detection\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.19"
  },
  "widgets": {
   "application/vnd.jupyter.widget-state+json": {
    "state": {},
    "version_major": 2,
    "version_minor": 0
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
